export const styles = {
  container: {
    height: "90vh",
    width: "100vw",
  } as React.CSSProperties,
  parentContainer: {
    display: "flex",
    position: "relative",
    height: "98vh",
    width: "100vw",
    justifyContent: "center",
    alignItems: "center",
    border: "solid 1px",
    overflowX: "hidden",
  } as React.CSSProperties,
  user: {
    position: "absolute",
    bottom: 50,
    right: 15,
    fontSize: 14,
    fontWeight: 500,
    color: "#E0E0E0",
    transition: `all 2s`,
  } as React.CSSProperties,
  views: {
    position: "absolute",
    bottom: 130,
    right: 15,
    fontSize: 14,
    fontWeight: 500,
    color: "#E0E0E0",
    transition: `all 2s`,
  } as React.CSSProperties,
  title: {
    position: "absolute",
    bottom: 90,
    right: 15,
    fontSize: 14,
    fontWeight: 500,
    color: "#E0E0E0",
    transition: `all 2s`,
  } as React.CSSProperties,
  nameBlock: {
    position: "absolute",
    display: "flex",
    fontSize: 20,
    fontWeight: 700,
    top: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "white",
    height: "100vh",
    width: "100vw",
    color: "black",
    transition: `all 2s`,
    overflow: "hidden",
  } as React.CSSProperties,
};
